version: "3.4"

services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "bank-account-kafka"
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - kafka-network

  mongo:
    image: "mongo:latest"
    container_name: "bank-account-mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - mongo-network

  mongo-express:
    image: "mongo-express:latest"
    container_name: "bank-account-mongo-express"
    restart: always
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=bank-account-mongo
    networks:
      - mongo-network
    depends_on:
      - mongo

volumes:
  kafka_data:
    driver: local
  mongo_data:
    driver: local

networks:
  kafka-network:
    driver: bridge
  mongo-network:
    driver: bridge
