version: "3.4"

services:
  mysql:
    image: "mysql:latest"
    container_name: "bank-account-mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bankaccount
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=secret
    networks:
      - mysql-network

  adminer:
    image: "adminer:latest"
    container_name: "bank-account-adminer"
    restart: always
    ports:
      - "8084:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=bank-account-mysql
    networks:
      - mysql-network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  mysql-network:
    driver: bridge
